import { MigrationInterface, QueryRunner } from "typeorm";

export class SeedTags1730245198764 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        // tags without categories
        await queryRunner.query(`
            INSERT INTO "alcs"."tag" ("audit_deleted_date_at", "audit_created_at", "audit_updated_at", "audit_created_by", "audit_updated_by", "name") VALUES 
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Aggregate Extraction'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Animal Shelter'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Aquaculture'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Area-Wide Filling'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Auto Services'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Bamboo'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Boundary Adjustment'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Café / Bistro / Restaurant'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Camp'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Campground / RV Park'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Cannabis'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Care Facility'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Cement / Asphalt / Concrete Plant'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Cemetery'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Civic'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Commercial'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Compost'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Controlled Environment Structure'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Dairy'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Eggs'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Emergency Works'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Endorsement'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Equestrian'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Event'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Exhibition / Festival'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Farm Road'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Farm Structure'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Fill Placement'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Fire Services'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Flood / Erosion Mitigation'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Forage / Hay'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Forestry Product'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Golf Course'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Grain'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Greenhouse'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Hall'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Home Occupation'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Hospital / Healthcare'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Industrial'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Land Development Works'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Leasehold Subdivision'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Lodge / Resort'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Lounge'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Milk / Butter / Cheese'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Mining'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Mushroom / Truffle'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Nursery'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Other Structure'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Park'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Parking'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Pet Boarding'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Pet Services'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Placer Mining'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Processing'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Religious'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Research'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Retail Sales'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Retroactive'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'School / University'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Seafood'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Soil Blending'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Soil Removal'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Sports Facility'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Storage'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Tourism'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Tree Fruit'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Turf Farm'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Vegetable'),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Vineyard');
        `);
        
        // tags with categories
        await queryRunner.query(`
            INSERT INTO "alcs"."tag" ("audit_deleted_date_at", "audit_created_at", "audit_updated_at", "audit_created_by", "audit_updated_by", "name", "category_uuid") VALUES 
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Accessory Structure', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Additional Residence', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Aviation', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Transportation')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Beef', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Meat')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Biogas', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Energy Production')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Blackberry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Blueberry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Brewery', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Alcohol')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Cranberry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Distillery', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Alcohol')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Driveway', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Electric', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Utilities')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Geothermal', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Energy Production')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Goat / Sheep', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Meat')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Haskap Berry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Landscaping', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Meadery', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Alcohol')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Mobile Home Park', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Oil / Gas', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Energy Production')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Pigs / Hogs', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Meat')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Pool', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Poultry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Meat')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Principal Residence', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Principal Residence > 500m2', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Railway', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Transportation')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Raspberry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Reside & Replace', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Road', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Transportation')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Sewage Infrastructure', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Utilities')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Solar', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Energy Production')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Stormwater Infrastructure', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Utilities')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Strawberry', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Berries')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Telecommunications', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Utilities')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Temporary Foreign Worker Housing', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Residential')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Trail', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Transportation')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Water Infrastructure', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Utilities')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Wind', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Energy Production')),
            (NULL, NOW(), NULL, 'migration_seed', NULL, 'Winery', (SELECT "uuid" FROM "alcs"."tag_category" WHERE "name" = 'Alcohol'));
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // N/A
    }

}
