# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/alcs-frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ALCS-000"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # TypeScript version is constrained to <5.5.0 as @angular-devkit/build-angular@17.3.x
      # requires typescript@">=5.2 <5.5". This prevents dependabot from suggesting incompatible updates.
      - dependency-name: "typescript"
        versions: [">=5.5.0"]
      # zone.js version is constrained to ~0.14.0 as required by @angular/core@17.3.x
      - dependency-name: "zone.js"
        versions: [">=0.15.0"]
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/portal-frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ALCS-000"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # TypeScript version is constrained to <5.5.0 as @angular-devkit/build-angular@17.3.x
      # requires typescript@">=5.2 <5.5". This prevents dependabot from suggesting incompatible updates.
      - dependency-name: "typescript"
        versions: [">=5.5.0"]
      # zone.js version is constrained to ~0.14.0 as required by @angular/core@17.3.x
      - dependency-name: "zone.js"
        versions: [">=0.15.0"]
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/services"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ALCS-000"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # reflect-metadata version is constrained to ~0.1.13 as required by automapper-classes@8.7.12
      - dependency-name: "reflect-metadata"
        versions: [">=0.2.0"]
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
