export enum AUTH_ROLE {
  ADMIN = 'Admin',
  APP_SPECIALIST = 'Application Specialist',
  COMMISSIONER = 'Commissioner',
  LUP = 'LUP',
  GIS = 'GIS',
  AGROLOGIST = 'Agrologist',
  SOIL_OFFICER = 'Soil Officer',
}

export const ROLES_ALLOWED_APPLICATIONS = [
  AUTH_ROLE.ADMIN,
  AUTH_ROLE.LUP,
  AUTH_ROLE.APP_SPECIALIST,
  AUTH_ROLE.GIS,
  AUTH_ROLE.AGROLOGIST,
  AUTH_ROLE.SOIL_OFFICER,
];

export const ROLES_ALLOWED_BOARDS = ROLES_ALLOWED_APPLICATIONS;
export const ROLES_ALLOWED_ARCHIVE = ROLES_ALLOWED_BOARDS;
export const ANY_AUTH_ROLE = Object.values(AUTH_ROLE);
export const ROLES_ALLOWED_SEARCH = [...ROLES_ALLOWED_APPLICATIONS, AUTH_ROLE.COMMISSIONER];
export const ANY_ROLE_BUT_COMMISSIONER = Object.values(AUTH_ROLE).filter((role) => role !== AUTH_ROLE.COMMISSIONER);
