kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: alcs-api
spec:
  to:
    kind: Service
    name: alcs-api
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None