#####################
# DATABASE MIGRATION 
#####################

FROM node:20-alpine As development

WORKDIR /opt/app-root/

# OpenShift fixes
RUN chmod og+rwx /opt/app-root/ /var/run
ENV NPM_CONFIG_USERCONFIG=/opt/app-root/.npmrc
RUN npm config set cache $/opt/app-root/.npm

COPY package*.json ./

RUN npm ci

ARG environment=production

ENV NODE_ENV ${environment}

ARG NEST_APP=alcs
ENV NEST_APP=${NEST_APP}

COPY . .

CMD [ "./migrate.sh" ]