FROM node:24-alpine AS development

WORKDIR /opt/app-root/
RUN chown node:node /opt/app-root/

COPY --chown=node:node package*.json ./

RUN npm ci --ignore-scripts

COPY --chown=node:node . .

CMD ["npm", "run", "start:dev"]
