export const NFU_SUBTYPES_OPTIONS = [
  { label: 'Accessory Buildings', value: 'Accessory Buildings' },
  { label: 'Additional Dwelling(s)', value: 'Additional Dwelling(s)' },
  { label: 'Additional Structures for Farm Help', value: 'Additional Structures for Farm Help' },
  { label: 'Agricultural Land Use Remnant', value: 'Agricultural Land Use Remnant' },
  { label: 'Agricultural Lease', value: 'Agricultural Lease' },
  { label: 'Agricultural Subdivision Remnant', value: 'Agricultural Subdivision Remnant' },
  { label: 'Airports and Aviation related', value: 'Airports and Aviation related' },
  { label: 'Alcohol Processing', value: 'Alcohol Processing' },
  { label: 'Animal Boarding and Services', value: 'Animal Boarding and Services' },
  { label: 'Auto Services', value: 'Auto Services' },
  { label: 'Beef', value: 'Beef' },
  { label: 'Campground (Private) & RV Park', value: 'Campground (Private) & RV Park' },
  { label: 'Care Facilities', value: 'Care Facilities' },
  { label: 'Cement/ Asphalt/Concrete Plants', value: 'Cement/ Asphalt/Concrete Plants' },
  { label: 'Cemeteries', value: 'Cemeteries' },
  { label: 'Churches & Bible Schools', value: 'Churches & Bible Schools' },
  { label: 'Civic - other', value: 'Civic - other' },
  { label: 'Civic Facilities and Buildings', value: 'Civic Facilities and Buildings' },
  { label: 'Commercial - other', value: 'Commercial - other' },
  { label: 'Composting', value: 'Composting' },
  { label: 'Dairy', value: 'Dairy' },
  { label: 'Deposition/Fill (All Types)', value: 'Deposition/Fill (All Types)' },
  { label: 'Golf Course', value: 'Golf Course' },
  { label: 'Grain & Forage', value: 'Grain & Forage' },
  { label: 'Electrical Power Distribution Systems', value: 'Electrical Power Distribution Systems' },
  { label: 'Greenhouses', value: 'Greenhouses' },
  { label: 'Electrical Power Facilities', value: 'Electrical Power Facilities' },
  { label: 'Exhibitions and Festivals', value: 'Exhibitions and Festivals' },
  { label: 'Subdivision Special Categories', value: 'Subdivision Special Categories' },
  { label: 'Food and Beverage Services', value: 'Food and Beverage Services' },
  { label: 'Subdivision Special Categories (Lease)', value: 'Subdivision Special Categories (Lease)' },
  { label: 'Food Processing (non-meat)', value: 'Food Processing (non-meat)' },
  { label: 'Industrial - other', value: 'Industrial - other' },
  { label: 'Land Use Remnant', value: 'Land Use Remnant' },
  { label: 'Livestock-Unspecified', value: 'Livestock-Unspecified' },
  { label: 'Logging Operations', value: 'Logging Operations' },
  { label: 'Lumber Manufacturing and Re-manufacturing', value: 'Lumber Manufacturing and Re-manufacturing' },
  { label: 'Meat and Fish Processing (+abattoir)', value: 'Meat and Fish Processing (+abattoir)' },
  { label: 'Mining', value: 'Mining' },
  { label: 'Misc. Agricultural Use', value: 'Misc. Agricultural Use' },
  { label: 'Mixed Ag Uses', value: 'Mixed Ag Uses' },
  { label: 'Mixed Uses', value: 'Mixed Uses' },
  { label: 'Mobile Home Park', value: 'Mobile Home Park' },
  { label: 'Multi Family-Apartments/Condominiums', value: 'Multi Family-Apartments/Condominiums' },
  { label: 'Office Building (Primary Use)', value: 'Office Building (Primary Use)' },
  { label: 'Oil and Gas Activities', value: 'Oil and Gas Activities' },
  { label: 'Other Uses', value: 'Other Uses' },
  { label: 'Other-Undefined', value: 'Other-Undefined' },
  { label: 'Parks & Playing Fields', value: 'Parks & Playing Fields' },
  { label: "Parks-All Types operated by Local Gov't", value: "Parks-All Types operated by Local Gov't" },
  { label: 'Pigs/Hogs', value: 'Pigs/Hogs' },
  { label: 'Poultry', value: 'Poultry' },
  { label: 'Public Transportation Facilities', value: 'Public Transportation Facilities' },
  { label: 'Railway', value: 'Railway' },
  { label: 'Recreational - other', value: 'Recreational - other' },
  { label: 'Research Facilities', value: 'Research Facilities' },
  { label: 'Residential - other', value: 'Residential - other' },
  { label: 'Roads', value: 'Roads' },
  { label: 'Sand & Gravel', value: 'Sand & Gravel' },
  { label: 'Sanitary Land Fills', value: 'Sanitary Land Fills' },
  { label: 'Schools & Universities', value: 'Schools & Universities' },
  { label: 'Sewage Treatment Facilities', value: 'Sewage Treatment Facilities' },
  { label: 'Sewer Distribution Systems', value: 'Sewer Distribution Systems' },
  { label: 'Shopping Centre', value: 'Shopping Centre' },
  { label: 'Small Fruits-Berries', value: 'Small Fruits-Berries' },
  { label: 'Sports Facilities - commercial', value: 'Sports Facilities - commercial' },
  { label: 'Sports Facilities - municipal', value: 'Sports Facilities - municipal' },
  { label: 'Storage & Warehouse', value: 'Storage & Warehouse' },
  { label: 'Store (Retail - All Types)', value: 'Store (Retail - All Types)' },
  { label: 'Telephone and Telecommunications', value: 'Telephone and Telecommunications' },
  { label: 'Tourist Accommodations', value: 'Tourist Accommodations' },
  { label: 'Trails', value: 'Trails' },
  { label: 'Transportation - other', value: 'Transportation - other' },
  { label: 'Tree Fruits', value: 'Tree Fruits' },
  { label: 'Turf Farm', value: 'Turf Farm' },
  { label: 'Vegetable & Truck', value: 'Vegetable & Truck' },
  { label: 'Vineyard and Associated Uses', value: 'Vineyard and Associated Uses' },
  { label: 'Water Distribution Systems', value: 'Water Distribution Systems' },
  { label: 'Water or Sewer Distribution Systems (inactive)', value: 'Water or Sewer Distribution Systems (inactive)' },
  { label: 'Water Treatment Facilities', value: 'Water Treatment Facilities' },
  { label: 'Hall/Lodge (private)_', value: 'Hall/Lodge (private)_' },
  { label: 'Hospitals, Health Centres (Incl Private)', value: 'Hospitals, Health Centres (Incl Private)' },
  { label: 'Farm Help Accommodation', value: 'Farm Help Accommodation' },
  { label: 'Gas and Other Distribution Pipelines', value: 'Gas and Other Distribution Pipelines' },
  { label: 'Energy Production', value: 'Energy Production' },
  { label: 'Energy Production', value: 'Energy Production' },
  { label: 'Lease', value: 'Lease' },
  {
    label: 'Storage and Warehouse Facilities (Indoor/Outdoor- Large Scale Structures)',
    value: 'Storage and Warehouse Facilities (Indoor/Outdoor- Large Scale Structures)',
  },
  { label: 'Work Camps or Associated Use', value: 'Work Camps or Associated Use' },
  { label: 'Miscellaneous Processing', value: 'Miscellaneous Processing' },
  { label: 'Events', value: 'Events' },
  { label: 'Sawmill', value: 'Sawmill' },
  { label: 'Fire Hall and associated uses', value: 'Fire Hall and associated uses' },
  { label: 'Alcohol Production Associated Uses', value: 'Alcohol Production Associated Uses' },
  { label: 'Cannabis Related Uses', value: 'Cannabis Related Uses' },
];

export const NFU_TYPES_OPTIONS = [
  {
    label: 'Agricultural / Farm',
    value: 'Agricultural / Farm',
  },
  {
    label: 'Civic / Institutional',
    value: 'Civic / Institutional',
  },
  {
    label: 'Commercial / Retail',
    value: 'Commercial / Retail',
  },
  {
    label: 'Industrial',
    value: 'Industrial',
  },
  {
    label: 'Other',
    value: 'Other',
  },
  {
    label: 'Recreational',
    value: 'Recreational',
  },
  {
    label: 'Residential',
    value: 'Residential',
  },
  {
    label: 'Transportation / Utilities',
    value: 'Transportation / Utilities',
  },
  {
    label: 'Unused',
    value: 'Unused',
  },
];
