#####################
# DATABASE MIGRATION 
#####################

FROM node:16.15-alpine As development

WORKDIR /opt/app-root/

COPY --chown=node:node package*.json ./

RUN npm ci

ARG environment=production

ENV NODE_ENV ${environment}

COPY --chown=node:node . .

USER node

CMD [ "npm", "run", "migration:run" ]