version: '3.6'
services:
  db:
    image: postgres:14.4-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgres
    networks: 
      - alcs
  db-admin:
    image: postgres:14.4-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5431:5432'
    volumes:
      - postgres-admin:/var/lib/postgres
    networks: 
      - alcs
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-admin
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "8081:8080"
    networks: 
      - alcs
    depends_on:
      - db-admin
volumes:
  postgres:
  postgres-admin:

networks: 
  alcs: 
    name: alcs 
    driver: bridge