version: '3.6'
services:
  db:
    image: postgres:14.4-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgres
    networks: 
      - alcs

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - alcs

  pgtap:
    image: hbpmip/pgtap:1.0.0-2
    environment:
      - DATABASE=postgres
      - USER=postgres
      - PASSWORD=postgres
    depends_on:
      - db
    command:
      - cp /mnt/** /test
    volumes:
      - ./test/pgtap:/test
    networks: 
      - alcs

volumes:
  postgres:

networks: 
  alcs: 
    name: alcs 
    driver: bridge