FROM node:16.15-alpine As development

WORKDIR /opt/app-root/
RUN chown node:node /opt/app-root/

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

CMD ["npm", "run", "start:dev"]