import { MigrationInterface, QueryRunner } from 'typeorm';

export class addAppStatus1669680023877 implements MigrationInterface {
  name = 'addAppStatus1669680023877';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "portal"."application_status" ("audit_deleted_date_at" TIMESTAMP WITH TIME ZONE, "audit_created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "audit_updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "audit_created_by" character varying NOT NULL, "audit_updated_by" character varying, "label" character varying NOT NULL, "code" text NOT NULL, "description" text NOT NULL, CONSTRAINT "UQ_ceabbf8054480a33932d3b6bbbc" UNIQUE ("description"), CONSTRAINT "PK_0c826eba913d2983a4ef7a0af79" PRIMARY KEY ("code"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ADD "status_code" text NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_document" DROP CONSTRAINT "FK_92f7df78b61a235c89d08c34e3b"`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application_document"."application_file_number" IS 'File Number generated by ALCS system'`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."file_number" IS 'File Number generated by ALCS system'`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."applicant" IS 'The Applicants name on the application'`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ALTER COLUMN "local_government_uuid" DROP NOT NULL`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."local_government_uuid" IS 'UUID from ALCS System of the Local Government'`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_document" ADD CONSTRAINT "FK_92f7df78b61a235c89d08c34e3b" FOREIGN KEY ("application_file_number") REFERENCES "portal"."application"("file_number") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ADD CONSTRAINT "FK_0c826eba913d2983a4ef7a0af79" FOREIGN KEY ("status_code") REFERENCES "portal"."application_status"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ADD "created_by_uuid" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ADD CONSTRAINT "FK_aa854b54da2bcb599ba88473c53" FOREIGN KEY ("created_by_uuid") REFERENCES "portal"."user"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "portal"."application" DROP CONSTRAINT "FK_aa854b54da2bcb599ba88473c53"`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" DROP COLUMN "created_by_uuid"`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" DROP CONSTRAINT "FK_0c826eba913d2983a4ef7a0af79"`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_document" DROP CONSTRAINT "FK_92f7df78b61a235c89d08c34e3b"`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."local_government_uuid" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" ALTER COLUMN "local_government_uuid" SET NOT NULL`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."applicant" IS NULL`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application"."file_number" IS NULL`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application_document"."application_file_number" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_document" ADD CONSTRAINT "FK_92f7df78b61a235c89d08c34e3b" FOREIGN KEY ("application_file_number") REFERENCES "portal"."application"("file_number") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" DROP COLUMN "status_code"`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application" DROP COLUMN "updated_at"`,
    );
    await queryRunner.query(`DROP TABLE "portal"."application_status"`);
  }
}
