import { MigrationInterface, QueryRunner } from 'typeorm';

export class addApplicationToOwner1674502507511 implements MigrationInterface {
  name = 'addApplicationToOwner1674502507511';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "portal"."application_owner" ADD "application_file_number" character varying NOT NULL`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application_owner"."application_file_number" IS 'File Number generated by ALCS system'`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_owner" ADD CONSTRAINT "FK_8104e51d0d9d1e920cd0f6df17c" FOREIGN KEY ("application_file_number") REFERENCES "portal"."application"("file_number") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "portal"."application_owner" DROP CONSTRAINT "FK_8104e51d0d9d1e920cd0f6df17c"`,
    );
    await queryRunner.query(
      `COMMENT ON COLUMN "portal"."application_owner"."application_file_number" IS 'File Number generated by ALCS system'`,
    );
    await queryRunner.query(
      `ALTER TABLE "portal"."application_owner" DROP COLUMN "application_file_number"`,
    );
  }
}
