import { AutoMap } from '@automapper/classes';
import {
  BaseEntity,
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Document } from '../../document/document.entity';
import { Application } from '../application.entity';

export enum DOCUMENT_TYPE {
  CERTIFICATE_OF_TITLE = 'certificateOfTitle',
  RESOLUTION_DOCUMENT = 'reviewResolutionDocument',
  STAFF_REPORT = 'reviewStaffReport',
  REVIEW_OTHER = 'reviewOther',
}

export const DOCUMENT_TYPES = [
  DOCUMENT_TYPE.CERTIFICATE_OF_TITLE,
  DOCUMENT_TYPE.RESOLUTION_DOCUMENT,
  DOCUMENT_TYPE.STAFF_REPORT,
  DOCUMENT_TYPE.REVIEW_OTHER,
];

@Entity()
export class ApplicationDocument extends BaseEntity {
  constructor(data?: Partial<ApplicationDocument>) {
    super();
    if (data) {
      Object.assign(this, data);
    }
  }

  @AutoMap()
  @PrimaryGeneratedColumn('uuid')
  uuid: string;

  @Column()
  type: string;

  @ManyToOne(() => Application, { nullable: false })
  application: Application;

  @Column({
    comment: 'File Number generated by ALCS system',
  })
  applicationFileNumber: string;

  @OneToOne(() => Document, {
    nullable: false,
    cascade: true,
    onDelete: 'CASCADE',
  })
  @JoinColumn()
  document: Document;
}
