{{- $redisPassword := (randAlphaNum 32) | b64enc }}
{{- $secretName := print (include "redis.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    template.openshift.io/expose-password: "{.data['database-password']}"
  name: {{ $secretName }}
  labels: {{ include "redis.labels" . | nindent 4 }}
stringData:
  database-password: {{ $redisPassword }}
{{- end }}