name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
    secrets: inherit
    concurrency:
      group: deploy-test
      cancel-in-progress: true
  deploy-prod:
    needs: deploy-test
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit
    concurrency:
      group: deploy-prod
      cancel-in-progress: true