name: CD
on:
  push:
    branches:
      - cicd
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev