name: CI

on:
  push:
    branches:
      - cicd
env:
  API_IMAGE_NAME: alcs-api
  MIGRATE_IMAGE_NAME: alcs-migrate
  FE_IMAGE_NAME: alcs-frontend
  
jobs:
  build-api:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to OpenShift
      run: |
        oc login --token=${{ secrets.oc_token }} --server=${{ secrets.oc_server }}
        docker login -u `oc whoami` -p `oc whoami --show-token` ${{ secrets.registry_url }}

    - name: Build and push API
      run: |
        IMAGE_NAME=${{ secrets.registry_url }}/${{ secrets.license-plate }}-tools/${{ env.API_IMAGE_NAME }}
        docker build -t $IMAGE_NAME:${{ github.run_number }} alcs-api
        docker push $IMAGE_NAME:${{ github.run_number }}


    # - name: Repository Dispatch
    #   uses: peter-evans/repository-dispatch@v1  
    #   with:
    #     token: ${{ secrets.PAT }}
    #     repository: ${{ github.actor }}/argocd-node-app-config
    #     event-type: new-image
    #     client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}'