name: CI
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-alcs-frontend:
    defaults:
      run:
        working-directory: alcs-frontend
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["18"]
    name: ALCS Frontend Tests - ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
  test-portal-frontend:
    defaults:
      run:
        working-directory: portal-frontend
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["18"]
    name: Portal Frontend Tests - ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
  test-api:
    defaults:
      run:
        working-directory: services
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["20"]
    name: API Tests - ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run test
