name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  API_IMAGE_NAME: alcs-api
  MIGRATE_IMAGE_NAME: alcs-migrate
  FE_IMAGE_NAME: alcs-frontend
  PORTAL_API_IMAGE_NAME: alcs-portal-api
  GITOPS_REPO: bcgov-c/tenant-gitops-a5cf88

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Lowercase repo owner
        id: lowercase_repo_owner
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Authenticate to OpenShift
        run: |
          DOCKER_IMAGE=ghcr.io/${{ steps.lowercase_repo_owner.outputs.lowercase }}/alcs-api
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}

      - name: Import Images
        run: |
          import() { \
            echo "Importing $1" ; \
            oc import-image $1:${{ github.sha }} --from ghcr.io/bcgov/$1:${{ github.sha }} -n ${{secrets.LICENSE_PLATE}}-tools ;}

          import alcs-api
          import alcs-frontend
          import alcs-migrate
          import alcs-portal-frontend

      - name: Checkout Gitops repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
          repository: ${{ env.GITOPS_REPO }}

      - name: "Configure git"
        # From https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update API Image
        id: api-image-update
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "image-registry.apps.silver.devops.gov.bc.ca/a5cf88-tools/alcs-api:${{ github.sha }}"' -i namespaces/dev/images-api_patch.yaml

      - name: Update Migrate Image
        id: migrate-image-update
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "image-registry.apps.silver.devops.gov.bc.ca/a5cf88-tools/alcs-migrate:${{ github.sha }}"' -i namespaces/dev/images-migrate_patch.yaml

      - name: Update ALCS Frontend Image
        id: fe-image-update
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "image-registry.apps.silver.devops.gov.bc.ca/a5cf88-tools/alcs-frontend:${{ github.sha }}"' -i namespaces/dev/images-alcs_patch.yaml

      - name: Update Portal Frontend Image
        id: portal-fe-image-update
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "image-registry.apps.silver.devops.gov.bc.ca/a5cf88-tools/alcs-portal-frontend:${{ github.sha }}"' -i namespaces/dev/images-portal_patch.yaml

      - name: Commit and push update
        run: |
          git commit -am "${{ github.sha }}"
          git push origin
