name: OWASP Zap API Scan
on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Zap API Scan
    steps:
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          target: 'https://alcs-dev-api.apps.silver.devops.gov.bc.ca'
          issue_title: OWASP Zap API Results